const Screens = {
  SPLASH: `SPLASH`,
  HOME: `HOME`,
  STORY: `STORY`,
  STORIES_LIST: `STORIES_LIST`,
  AUTHOR: `AUTHOR`,
  AUTHORS_LIST: `AUTHORS_LIST`,
  TRANSLATOR: `TRANSLATOR`,
  TRANSLATORS_LIST: `TRANSLATORS_LIST`,
  SPEAKER: `SPEAKER`,
  SPEAKERS_LIST: `SPEAKERS_LIST`,
};

export default Screens;
